services:
  ecosolve:
    image: ${DOCKER_REGISTRY-}ecosolve
    build:
      context: .
      dockerfile: EcoSolve/Dockerfile
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/spidev0.0:/dev/spidev0.0
    restart: unless-stopped
